name: Backend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码仓库
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录（可选，根据需求）

      # 设置 Java 环境（安装 Java 8）
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          java-package: 'jdk'  # 显式指定 JDK

      # 缓存 Maven 依赖以加速构建
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # 使用 Maven 编译打包（跳过测试）
      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      # 列出目标目录以调试
      - name: List target dir for debug
        run: ls -lh target/

      # 将构建产物部署到远程服务器
      - name: Deploy to Server via SCP and SSH
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          set -e

          echo "Write SSH key"
          cat <<EOF > /tmp/deploy_key.pem
          $SERVER_SSH_KEY
          EOF
          chmod 600 /tmp/deploy_key.pem

          echo "List JAR files"
          ls -lh target/

          echo "Test SCP deployment"
          scp -v -o StrictHostKeyChecking=no -i /tmp/deploy_key.pem target/*.jar $SERVER_USER@$SERVER_HOST:/home/jojo/ics3u-server/app.jar

          echo "Test SSH kill process"
          ssh -v -o StrictHostKeyChecking=no -i /tmp/deploy_key.pem $SERVER_USER@$SERVER_HOST "
            echo 'Checking running processes...'
            ps aux | grep '[j]ava.*app.jar'
            echo 'Killing existing processes...'
            pkill -f 'java -jar.*app.jar' || kill -9 \$(pgrep -f 'java -jar.*app.jar') || true
            sleep 2  # 等待进程完全停止
          "

          echo "Test SSH start server"
          ssh -v -o StrictHostKeyChecking=no -i /tmp/deploy_key.pem $SERVER_USER@$SERVER_HOST "
            echo 'Launching new jar...'
            chmod 755 /home/jojo/ics3u-server/app.jar  # 确保执行权限
            nohup java -Xmx512m -jar /home/jojo/ics3u-server/app.jar > /home/jojo/ics3u-server/server.log 2>&1 &
            disown
            echo 'Server started.'
          "