name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: List target dir for debug
        run: ls -lh target/

      - name: Upload JAR to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "target/ics3u-assignment-server-*.jar"
          target: "/home/jojo/ics3u-server/"
          strip_components: 1

      - name: Restart Spring Boot server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          # ✅ 不加 request_pty
          # ❌ request_pty: true
          timeout: 10m
          command_timeout: 5m
          script: |
            echo "Stopping existing server..."
            pkill -f 'ics3u-assignment-server' || true
            sleep 1
            echo "Launching new jar..."
            nohup java -jar /home/jojo/ics3u-server/ics3u-assignment-server-*.jar \
              > /home/jojo/ics3u-server/server.log 2>&1 &
            echo "Server started."
      
